db:
  image: mariadb
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD=the_db_root_password
  - MYSQL_USER=c5dbadmin
  - MYSQL_PASSWORD=the_db_user_password
  - MYSQL_DATABASE=c5db
  log_opt: 
    max-size: "256k"
    max-file: "10"
  # host volume
  volumes:
    - ./data/var/lib/mysql:/var/lib/mysql

web:
  image: bacluc/concrete5.8
  restart: always
  ports:
  - "8080:80"
  - "8443:443"
  links:
  - db
  log_opt:
    max-size: "512k"
    max-file: "50"
  # host volumes 
  volumes:
    - ./data/etc/apache2:/etc/apache2
    - ./data/var/www/html:/var/www/html
